### ISSUE TITLE
Licence on the code?

### ISSUE THREAD

**Issue by jpaguerre** [ingowald/cudaKDTree#10]
Hello,

This is a nice project. Do you have a specific licence on this code?
We are thinking on using it in Advanced Computer Graphics class (UdelaR), where students will code Photon Mapping using OptiX. I'm guessing cudaKDTree should be ideal in this case. 

Please let me know if we have permissions for this.

Thanks,
José Aguerre

**Comment by ingowald** [comment]
Jose,
I didn't (yet) put an explicit license file in the project, but all the files have apache license headers, so I'd say it's fairly safe to use it for whatever you want :-). I'm currently working on some more cleanups to the latest devel branch that'll hopefully drop this week, but other than that sure, go ahead! 

BTW: If you do want to use OptiX for your project, might I also recommend my OWL project (https://github.com/owl-project/owl); it'll make your live quite a bit easier ...

**Comment by ingowald** [comment]
marking this as resolved
