### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by whuzs** [ingowald/cudaKDTree#11]
Thanks for such a great job, but when I compile the project, an error occurs“spatial-kdtree.h:20:10: fatal error: cub/cub.cuh: No such file or directory
 #include <cub/cub.cuh>
”
my cuda version is 10.1

**Comment by ingowald** [comment]
Thanks, I'll check on cuda version requirements for cub.
10.1 is pretty dated though:-)

**Comment by whuzs** [comment]
Yes, I updated my cuda version to 11.4 and it compiles fine
