### ISSUE TITLE
Problem Adding Library to CMake project

### ISSUE THREAD

**Issue by nico-mayora** [ingowald/cudaKDTree#24]
Hi, we've been making an OptiX path tracer with photon mapping for a university project. Using CMake for building and CLion for writing our code, we've decided to use this library for storing and retrieving the photons (thanks for developing this, and OWL, very helpful!).

We've been able to succesfully build and run the tests for this library stand-alone. However, when adding it to our existing codebase and running it all, it fails miserably, printing out errors like these:

```
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.41.34120\include\cmath(38): error: the global scope has no "acosf"
      return :: acosf(_Xx);
                ^
```
(there's _hundreds_ of lines like these).

This is preceded by a call to `nvcc.exe`, so my theory is that `nvcc` is attempting to complile C++ code for MSVC's implementation for some reason, and running into problems.

We've been trying everything we've come up with to fix this issue, but to no avail. We'd be very grateful if you could lend a hand coming up with a solution. The code in question is in https://github.com/nico-mayora/photon-mapping. To attempt to add CudaKDTree, we've done the exact same as with OWL in `CMakeLists.txt`. In addition, we included a `include_directories(${cudakdtree_dir}/cukd)` to be able to see the header files. If you need more information I'd be happy to provide it.

**Comment by ingowald** [comment]
Hey - thanks for reporting this, I'll have a look. 
I"m more of a linux user, so not an expert in VS, but I can reproduce that on another machine when i get home. First guess is that it's some missing include of "math.h" - when I look at cmath it seems to have "acos(double)", but maybe(?) not "acosf(float)" ... but i'll have to have a look to be sure.

**Comment by ingowald** [comment]
Could you check if you have c++-11 enabled?

According to cppreference (https://en.cppreference.com/w/cpp/numeric/math/acos) the float version of acos (acosf) is only in cmath since c++-11. Kind-of ridiculous if cmath is supposed to replace math.h (in which cosf exists since before dinosaurs roamed the earth), but hey .... if that's what cppreference says it's worth checking.

**Comment by nico-mayora** [comment]
We were using C++17 features so I think we we're sorted in that aspect. FWIW I added `set_property(TARGET rayTracer PROPERTY CXX_STANDARD 17)` to our CMakeLists.txt just in case, but the issue persists. For replicating the problem you can refer to https://github.com/nico-mayora/photon-mapping/tree/kdtree. Thanks for your swift response.

**Comment by back2yes** [comment]
I am using vs, met with similar problems here. I managed to build it by put a dummy.cpp in the project folder (to make it a shared library than a header only library). It compiles with no error, but the building time became quite long. Do you guys have better solutions?

**Comment by nico-mayora** [comment]
@back2yes Would you mind going over what you did in more detail, or providing the work-around you mentioned so I can give it a go, and perhaps iterating on it?

**Comment by ingowald** [comment]
Ah. Finally found some time to actually get my windows machine back to a state where i can actually look at this.

What it looks _so far_ is that you're trying to include the (CUDA!) header file from cudakdtree from a "plain" c++ "hostcode.cxx". In that case, cmake will use visual studio c++ to compile that file - not cuda - and visual studio can only do C++, not cuda. Basically, cudaKDTree is a _cuda_ library, not a c++ library, and you should be using cuda to compile it, not a regular c++ compiler.

Now in theory, it should be possible to have cudakdtree's _header_ file such that it can be understood by msvc as well (you couldn't do the queries, but at least call the builder), and yes, that's what I usually do in other project ... and yes, that _should_ be the case here, too. I'll have to look into that, though, no idea what VS is choking on right now.

Should I not be able to get to that today, one (presumed but untested) workaround would be to rename your hostcode.cxx to hostcode.cu, in which case it should be compiled with cuda, which should be able to digest cudakdtree's headers.

**Comment by ingowald** [comment]
Digging deeping into this, it actually looks like the errors are coming from _owl_ header files, not cudakdtree?

**Comment by ingowald** [comment]
<groan>.
From your original message:
> In addition, we included a include_directories(${cudakdtree_dir}/cukd) to be able to see the header files.
I _know_ when I first read that it triggered _some_ sort of red flag, but didn't follow up on it right away ... but _that_ is actually the problem:
`cudakdtree` has all its header files in `<root>/cukd/*.h`, so they're supposed to be included as `<cukd/builder.h>` etc, not `<builder.h>`. Basically, the `"cukd/"` serves almost like a namespace. (cukd also exports an automatic include path, you shouldn't need to ever set one manually).
Anyway - the reason adding that include paths causes actual _issues_ is that in addition to `cukd/builder.h` there's also a `cukd/math.h`, and if you add a manual include search path to the cukd/ directory then visual studio will, when it includes its own <cmath>, automatically include _this_ header file (cause it's also called "math.h"), not the _system_-level math.h.

I'll go ahead and rename cukd/math.h to some other name where a name-conflict cannot as easily happen, but until then: do NOT add the include-directive to the cukd/ subdirectory, and the problem should go away. (can't fully test right now because I made a lot of changes to your code to track that down, but that _should_ fix it)

**Comment by nico-mayora** [comment]
Ah I gotcha. I'll give this a spin and get back to you. We've also encourtered some issues _not_ using `include_directories`.

**Comment by ingowald** [comment]
pls update cukd repo to latest version i just pushed. there were one or two minor __device__ functions that didn't compile in non-cuda compiler, which i just fixed. let me know if this works, please!

**Comment by ingowald** [comment]
Also let me know if you run into any issues with the `include_directories` - in theory using modern cmake that should never be required any more, so if it is something else is broken (but it could be on my side, so let me know if so). In that same vein i also just saw that cukd still used non-modern cmake for setting cxx standard to 14 - i also just fixed that. Either way - let me know :-)
(and thanks for reporting - can't fix bugs one's not aware of!)

**Comment by nico-mayora** [comment]
All right, we've tried multiple stuff and have the following to report:
- Pulled the latest commit with your fixed for this library.
- Removed `include_directories` from CMakeLists.txt.
- Changed the `#include` directive in `hostCode.cxx` to `#include <cukd/builder.h>`.
- We've also added the `foo` example from the README to our `hostCode.cxx` file.

This unfortunately resulted in the following errors (paraphrasing as I don't have the exact stacktrace at the moment):
These errors are reported by `cl.exe`.
- Unknown directive `#pragma unroll`
- Syntax error when `<<<...>>>` cuda syntax is encountered.

After renaming `hostCode.cxx` to `hostCode.cu`, and refactoring our syntax to be compatible, we've managed to compile the project. However, I think this solution is far from ideal.

**Comment by nico-mayora** [comment]
I managed to get the full error string
```
C:\PROGRA~1\MICROS~2\2022\COMMUN~1\VC\Tools\MSVC\1441~1.341\bin\Hostx64\x64\cl.exe  /nologo /TP -DNOMINMAX -IC:\Users\Nico\CLionProjects\testing\externals\owl -IC:\Users\Nico\CLionProjects\testing\externals\owl\owl\include -IC:\Users\Nico\CLionProjects\testing\externals\assimp\code\..\include -IC:\Users\Nico\CLionProjects\testing\cmake-build-release\externals\assimp\code\..\include -IC:\Users\Nico\CLionProjects\testing\externals\cudaKDTree -external:I"C:\ProgramData\NVIDIA Corporation\OptiX SDK 8.0.0\\include" -external:I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.6\include" -external:W0 /DWIN32 /D_WINDOWS /EHsc /O2 /Ob2 /DNDEBUG -std:c++17 -MD /showIncludes /FoCMakeFiles\rayTracer.dir\ray-tracer\src\hostCode.cxx.obj /FdCMakeFiles\rayTracer.dir\ /FS -c C:\Users\Nico\CLionProjects\testing\ray-tracer\src\hostCode.cxx
C:\Users\Nico\CLionProjects\testing\externals\cudaKDTree\cukd/builder_common.h(140): warning C4068: unknown pragma 'unroll'
C:\Users\Nico\CLionProjects\testing\externals\cudaKDTree\cukd/builder_thrust.h(477): error C2059: syntax error: '<'
C:\Users\Nico\CLionProjects\testing\externals\cudaKDTree\cukd/builder_thrust.h(477): note: the template instantiation context (the oldest one first) is
C:\Users\Nico\CLionProjects\testing\ray-tracer\src\hostCode.cxx(53): note: see reference to function template instantiation 'void cukd::buildTree<float3,cukd::default_data_traits<data_t,cukd::point_traits<_point_t>>>(data_t *,int,cukd::box_t<_point_t> *,cudaStream_t,cukd::GpuMemoryResource &)' being compiled
        with
        [
            data_t=float3,
            _point_t=float3
        ]
C:\Users\Nico\CLionProjects\testing\externals\cudaKDTree\cukd/builder.h(148): note: see reference to function template instantiation 'void cukd::buildTree_thrust<data_t,data_traits>(data_t *,int,cukd::box_t<_point_t> *,cudaStream_t,cukd::GpuMemoryResource &)' being compiled
        with
        [
            data_t=float3,
            data_traits=cukd::default_data_traits<float3,cukd::point_traits<float3>>,
            _point_t=float3
        ]
C:\Users\Nico\CLionProjects\testing\externals\cudaKDTree\cukd/builder_thrust.h(493): error C2059: syntax error: '<'
C:\Users\Nico\CLionProjects\testing\externals\cudaKDTree\cukd/builder_thrust.h(498): error C2059: syntax error: '<'
ninja: build stopped: subcommand failed.
```

**Comment by nico-mayora** [comment]
Closing this as we've managed to include the library changing `hostCode.cxx`'s filename to `hostCode.cu`.
