### ISSUE TITLE
cub::DeviceRadixSort or thrust::sort

### ISSUE THREAD

**Issue by mcmingchang** [ingowald/cudaKDTree#27]
In my previous experience, it has been shown that if sort is called multiple times in a short period of time, the latency of the cube library is much shorter than that of the thrust library. You can choose between cube:: DeviceRadixSort or cube:: DeviceSegmentedRadixSort. I wonder if you are interested in trying them out, and I look forward to your reply.

**Comment by ingowald** [comment]
Yes, it's usually better; i pretty much changed all my repos over to cub, i just haven't gotten around to doing that for cukd, yet.

**Comment by ingowald** [comment]
BTW - if you want to submit a PR that changes this library from thrust to cub, i'd be happy to merge it :-)

**Comment by mcmingchang** [comment]
I am still researching how to call knn and obtain the first N nearest sequences
