### ISSUE TITLE
GPU memory overflow

### ISSUE THREAD

**Issue by mcmingchang** [ingowald/cudaKDTree#29]
for (int i = 0; i < 100000; i++) {
    SpatialKDTree<float3, default_data_traits<float3>> tree;
    cukd::buildTree<float3, default_data_traits<float3>>(tree, pts, pt_num, buildConfig);
    cudaMemGetInfo(&freeMem, &totalMem);
    std::cout << "Used memory: " << (totalMem - freeMem) << " bytes\n";
    std::cout << "Add memory: " << (totalMem - freeMem) - lastMem << " bytes\n";
    lastMem = totalMem - freeMem;
}

**Comment by mcmingchang** [comment]
SpatialKDTree<float3, default_data_traits<float3>> tree;
for (int i = 0; i < 100000; i++) {
    if (tree.nodes) {
        cudaFree(tree.nodes);
        tree.nodes = nullptr;
        cudaFree(tree.primIDs);
        tree.primIDs = nullptr;
    }
    cukd::buildTree<float3, default_data_traits<float3>>(tree, pts, pt_num, buildConfig);
    
    cudaMemGetInfo(&freeMem, &totalMem);
    std::cout << "Used memory: " << (totalMem - freeMem) << " bytes\n";
    std::cout << "Add memory: " << (totalMem - freeMem) - lastMem << " bytes\n";
    lastMem = totalMem - freeMem;
}


My solution

**Comment by mcmingchang** [comment]
Although my solution solves GPU memory overflow, CUDAFree will slow down the entire computation speed. Is there a better solution?

**Comment by ingowald** [comment]
Two options:
a) the user provides the 'primID' memory to buildTree (only for spatialkdtree); then it's the user's responsibility to free that mem, or he can simply re-use it for successive runs.
b ) switching from cudamalloc/cudafree to cudamallocasync and cudafreeasync - then only the first malloc is expensive, and successive ones are cheap (not as cheap as 'a', but still pretty cheap)

**Comment by ingowald** [comment]
Just realized it's not just primID memory, but also node memory, which is a bit harder to control for because its size isn't predictable before the build. Maybe best solution is to provide a means for user to provide alloc() and free() routines (that could then user cudaFree), and document that these primID and node arrays need to be freed afterwards..

**Comment by ingowald** [comment]
I just pushed (devel) some changes where you'd pass a GPUMemoryResource (basically, a memory allocator/free'er object) to the spatial builder, as well as a free() method. I currently can't do any testing ATM, but changes were simple enough that I pushed, anyway - basically the entire allocate/free concept was already there in the 'regular' builders, so i just copied that over.
