### ISSUE TITLE
#define FCP2 1

### ISSUE THREAD

**Issue by whuzs** [ingowald/cudaKDTree#8]
What does this function do? i found enable this function but some case verify failed.

**Comment by ingowald** [comment]
That was/is an experimental traversal algorithm that fixed quite a few performance degenration issues for situations where many of the queries happen far away from the actual data points - for which the regular k-d tree traversal could suffer quite a bit. 
I've completely rewritten that in a different branch, so it's possible that the one in main is currently broken. I'll have a look

**Comment by ingowald** [comment]
can you tell me for what exactly it fails verification? any reproducer would help

**Comment by ingowald** [comment]
oh, wait, i remember how/when i fixed it in that other branch .... the bug isn't actually in the traversal, it's in the float atomic_min/max for computing the bouding box. if the initial bounding box is wrong then traversal misses some branches.
i'll fix this soon - just trying to do it with a minimum of changes so i don't end up in merge conflict purgatory later on - all that code got completely rewritten in that other branch. one sec.

**Comment by whuzs** [comment]
Thank you for your reply. Yes, I verified an error during my previous testing of testCaseID2, but it has now been fixed.
